import { Metadata } from 'next'
import Hero from '@/components/hero/Hero'
import Link from 'next/link'

import s from './Hire.module.sass'
import Content, { Copies, Links, Row } from '@/components/content/Content'

import Title from './title.mdx'

import Copies1 from './copies1.mdx'
import Copies2 from './copies2.mdx'
import Copies3 from './copies3.mdx'
import Copies4 from './copies4.mdx'

import Links1 from './links1.mdx'
import Links2 from './links2.mdx'
import Links3 from './links3.mdx'
import Separator from '@/components/separator/Separator'

export const metadata: Metadata = {
  title: 'About. Zafree.',
  description: 'Generated by create next app',
}

function Hire() {
  return (
    <>
      <Hero kicker="Hire me" title="I’m a design-minded front-end developer.">
        <h2 className={s.Hire__subheading}>
          Also called{' '}
          <Link
            href="https://bradfrost.com/blog/post/frontend-design/"
            target="_blank"
          >
            front-end designer
          </Link>
          , UI developers, UI engineer, or{' '}
          <Link
            href="https://snook.ca/archives/opinion/design-engineering"
            target="_blank"
          >
            design engineer
          </Link>
          .
        </h2>
        <p className={s.Hire__copy}>
          As a <em>[choose one of the above titles]</em>, I work on the{' '}
          <Link
            href="https://bradfrost.com/blog/post/frontend-design/"
            target="_blank"
          >
            front-end of the front-end
          </Link>
          . That is, my work lies at the intersection of design and back-end.
        </p>
      </Hero>
      <Content>
        <Row>
          <Title />
        </Row>
        <Row flex>
          <Copies>
            <Copies1 />
          </Copies>
          <Links>
            <Links1 />
          </Links>
        </Row>
        <Row flex>
          <Copies>
            <Copies2 />
          </Copies>
          <Links>
            <Links2 />
          </Links>
        </Row>
        <Separator />
        <Row flex>
          <Copies>
            <Copies3 />
          </Copies>
          <Links>
            <Links3 />
          </Links>
        </Row>
        <Separator />
        <Row>
          <Copies4 />
        </Row>
      </Content>
    </>
  )
}

export default Hire
