import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Hire. Zafree.',
  description: 'Generated by create next app',
}

function page() {
  return <h1>Hire</h1>
}

export default page
