import { Metadata } from 'next'
import Hero from '@/components/hero/Hero'
import Link from 'next/link'

import s from './Hire.module.sass'

export const metadata: Metadata = {
  title: 'About. Zafree.',
  description: 'Generated by create next app',
}

function page() {
  return (
    <>
      <Hero kicker="Hire me" title="I’m a design-minded front-end developer.">
        <h2 className={s.Hire__subheading}>
          Also called{' '}
          <Link
            href="https://bradfrost.com/blog/post/frontend-design/"
            target="_blank">
            front-end designer
          </Link>
          , UI developers, UI engineer, or{' '}
          <Link
            href="https://snook.ca/archives/opinion/design-engineering"
            target="_blank">
            design engineer
          </Link>
          .
        </h2>
        <p className={s.Hire__copy}>
          As a <em>[choose one of the above titles]</em>, I work on the{' '}
          <Link
            href="https://bradfrost.com/blog/post/frontend-design/"
            target="_blank">
            front-end of the front-end
          </Link>
          . That is, my work lies at the intersection of design and back-end.
        </p>
      </Hero>
      <div className="box"></div>
    </>
  )
}

export default page
