import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About. Zafree.',
  description: 'Generated by create next app',
}

function page() {
  return <h1>About</h1>
}

export default page
