import Hero from '@/components/hero/Hero'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Work. Zafree.',
  description: 'Generated by create next app',
}

function page() {
  return (
    <>
      <Hero
        kicker="My work"
        title="Insights into my work"
        subtitle="Such panic zone"
      />
      <div className="box"></div>
    </>
  )
}

export default page
